# Result: exception, 1 != 2

main () = assert (1 == 2) "1 != 2"